var ch2a = [{English: "a little", Romaji: "chotto", Hiragana: "ちょっと", Kanji: ""},
              {English: "It really helps", Romaji: "tasukarimasu", Hiragana: "たすかります", Kanji: ""},
              {English: "together", Romaji: "isshoni", Hiragana: "いっしょに", Kanji:""},
              {English: "here", Romaji: "koko", Hiragana: "ここ", Kanji: ""},
              {English: "there", Romaji: "soko", Hiragana: "そこ", Kanji: ""},
              {English: "over there", Romaji: "asoko", Hiragana: "あそこ", Kanji: ""},
              {English: "where", Romaji: "doko", Hiragana: "どこ", Kanji: ""},
              {English: "Where is it?", Romaji: "Doko desu ka?", Hiragana: "どこですか", Kanji: ""},
              {English: "this one", Romaji: "kore", Hiragana: "これ", Kanji: ""},
              {English: "that one(near listener)", Romaji: "sore", Hiragana: "それ", Kanji: ""},
              {English: "that one(over there)", Romaji: "are", Hiragana: "あれ", Kanji: ""},
              {English: "this", Romaji: "kono", Hiragana: "この", Kanji: ""},
              {English: "that(near listener) ~", Romaji: "sono", Hiragana: "その", Kanji: ""},
              {English: "that(over there)", Romaji: "ano", Hiragana: "あの", Kanji: ""},
              {English: "which", Romaji: "dono", Hiragana: "どの", Kanji: ""},
              {English: "white", Romaji: "shiroi", Hiragana: "しろい", Kanji: "白い"},
              {English: "university", Romaji: "daigaku", Hiragana: "だいがく", Kanji: "大学"},
              {English: "student", Romaji: "gakusei", Hiragana: "がくせい", Kanji: "学生"},
              {English: "bag", Romaji: "kaban", Hiragana: "かばん", Kanji: ""},
          ];
