var ch5b = [{English:"doctor", Romaji: "isha", Hiragana: "いしゃ", Kanji: " "},
            {English:"this week", Romaji: "konshuu", Hiragana: "こんしゅう", Kanji: "今週"},
            {English:"last week", Romaji: "senshuu", Hiragana: "せんしゅう", Kanji: "先週"},
            {English:"next week", Romaji: "raishuu", Hiragana: "らいしゅう", Kanji: "来週"},
            {English:"now", Romaji: "ima", Hiragana: "いま", Kanji: "今"},
            {English:"remember", Romaji: "otoidasu", Hiragana: "おもいだす", Kanji: " "},
            {English:"learn", Romaji: "narau", Hiragana: "ならう", Kanji: " "},
            {English:"to call", Romaji: "denwasuru", Hiragana: "でんわする/-します", Kanji: " "},
            {English:"to clean", Romaji: "soujisuru", Hiragana: "そうじする/-します", Kanji: "  "},
            {English:"to do laundry", Romaji: "sentakusuru", Hiragana: "せんたくする/-します", Kanji: " "},
            {English:"to worry", Romaji: "shinpaisuru", Hiragana: "しんぱいする/-します", Kanji: " "},
            {English:"to catch a cold", Romaji: "kazewohiku", Hiragana: "かぜをひく/-きます", Kanji: " "},
            {English:"usually, normally", Romaji: "itsumo", Hiragana: "いつも", Kanji: " "},
            {English:"very(casual)", Romaji: "yoku", Hiragana: "よく", Kanji: " "},
            {English:"usually", Romaji: "taitei", Hiragana: "たいてい", Kanji: " "},
            {English:"sometimes", Romaji: "tokidoki", Hiragana: "ときどき", Kanji: " "},
            {English:"not much", Romaji: "omari~nai", Hiragana: "あまり〜ない", Kanji: " "},
            {English:"not at all", Romaji: "zenzen~nai", Hiragana: "ぜんぜん〜ない", Kanji: " "},
            {English:"What happened?/What's wrong", Romaji: "Doushitandesuka", Hiragana: "どうしたんですか", Kanji: " "}
          ]
