var kanjiJ1 = [{English: "one", Romaji: "ichi", Hiragana: "いち", Kanji: "一"},
              {English: "two", Romaji: "ni", Hiragana: "に", Kanji: "二"},
              {English: "three", Romaji: "san", Hiragana: "さん", Kanji: "三"},
              {English: "four", Romaji: "yon", Hiragana: "よん", Kanji: "四"},
              {English: "five", Romaji: "go", Hiragana: "ご", Kanji: "語"},
              {English: "six", Romaji: "roku", Hiragana: "ろく", Kanji: "六"},
              {English: "seven", Romaji: "nana/shichi", Hiragana: "なな/しち", Kanji: "七"},
              {English: "eight", Romaji: "hachi", Hiragana: "はち", Kanji: "八"},
              {English: "nine", Romaji: "kyuu", Hiragana: "きゅう", Kanji: "九"},
              {English: "ten", Romaji: "jyuu", Hiragana: "じゅう", Kanji: "十"},]
